### PR TITLE
Add page and screen + fix tests

### PR DESCRIPTION
**Pull request by francisco**
Hey @sperand-io - can you take a look at this when you get a chance?

To recap, these are the changes included in this PR:
- Resolved the failing write_key validation tests due to changes in Calq's API response from 400 to 200 with status:rejected message
- Incorporated Calq's addition of the page and screen call including tests

### CODE REVIEW

**Comment by RRAway** [comment]
Just some feedback from our end. The changing of Calq's API response to 200 on failed write keys is a bug. It was changed away from 400, but it's meant to be 403 not the 200 you picked up. The rest of the payload (i.e. status: rejected) is still correct as per your tests.

**Comment by francisco** [comment]
Thanks for the update @RRAway. I changed the handling back to a 403 in the latest commit.

Francisco

**Comment by sperand-io** [comment]
@RRAway just to echo @francisco... thanks so much for jumping in there and letting us know!!

**Comment by RRAway** [comment]
Is this going to get merged in? It's been nearly 8 months since the original pull request. That seems a little excessive guys?

**Pull request merged**
